# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Render.ui'
#
# Created: Mon Apr 01 11:37:47 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(957, 730)
        self.gridLayout_2 = QtGui.QGridLayout(widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.filter_label = QtGui.QLabel(widget)
        self.filter_label.setObjectName("filter_label")
        self.horizontalLayout.addWidget(self.filter_label)
        self.all_rb = QtGui.QRadioButton(widget)
        self.all_rb.setObjectName("all_rb")
        self.horizontalLayout.addWidget(self.all_rb)
        self.comp_rb = QtGui.QRadioButton(widget)
        self.comp_rb.setObjectName("comp_rb")
        self.horizontalLayout.addWidget(self.comp_rb)
        self.mm_rb = QtGui.QRadioButton(widget)
        self.mm_rb.setObjectName("mm_rb")
        self.horizontalLayout.addWidget(self.mm_rb)
        self.paint_rb = QtGui.QRadioButton(widget)
        self.paint_rb.setObjectName("paint_rb")
        self.horizontalLayout.addWidget(self.paint_rb)
        self.roto_rb = QtGui.QRadioButton(widget)
        self.roto_rb.setObjectName("roto_rb")
        self.horizontalLayout.addWidget(self.roto_rb)
        self.others_rb = QtGui.QRadioButton(widget)
        self.others_rb.setObjectName("others_rb")
        self.horizontalLayout.addWidget(self.others_rb)
        self.refresh_Button = QtGui.QPushButton(widget)
        self.refresh_Button.setObjectName("refresh_Button")
        self.horizontalLayout.addWidget(self.refresh_Button)
        self.hide_checkbox = QtGui.QCheckBox(widget)
        self.hide_checkbox.setObjectName("hide_checkbox")
        self.horizontalLayout.addWidget(self.hide_checkbox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.start_date_lineEdit = QtGui.QLineEdit(widget)
        self.start_date_lineEdit.setObjectName("start_date_lineEdit")
        self.horizontalLayout_2.addWidget(self.start_date_lineEdit)
        self.start_date_toolButton = QtGui.QToolButton(widget)
        self.start_date_toolButton.setObjectName("start_date_toolButton")
        self.horizontalLayout_2.addWidget(self.start_date_toolButton)
        self.end_datelineEdit = QtGui.QLineEdit(widget)
        self.end_datelineEdit.setObjectName("end_datelineEdit")
        self.horizontalLayout_2.addWidget(self.end_datelineEdit)
        self.end_date_toolButton = QtGui.QToolButton(widget)
        self.end_date_toolButton.setObjectName("end_date_toolButton")
        self.horizontalLayout_2.addWidget(self.end_date_toolButton)
        self.line = QtGui.QFrame(widget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.render_comboBox = QtGui.QComboBox(widget)
        self.render_comboBox.setObjectName("render_comboBox")
        self.render_comboBox.addItem("")
        self.render_comboBox.addItem("")
        self.render_comboBox.addItem("")
        self.render_comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.render_comboBox)
        self.line_2 = QtGui.QFrame(widget)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.node_comboBox = QtGui.QComboBox(widget)
        self.node_comboBox.setObjectName("node_comboBox")
        self.node_comboBox.addItem("")
        self.node_comboBox.addItem("")
        self.node_comboBox.addItem("")
        self.node_comboBox.addItem("")
        self.node_comboBox.addItem("")
        self.node_comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.node_comboBox)
        self.line_3 = QtGui.QFrame(widget)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_2.addWidget(self.line_3)
        self.resolution_comboBox = QtGui.QComboBox(widget)
        self.resolution_comboBox.setObjectName("resolution_comboBox")
        self.resolution_comboBox.addItem("")
        self.resolution_comboBox.addItem("")
        self.resolution_comboBox.addItem("")
        self.resolution_comboBox.addItem("")
        self.resolution_comboBox.addItem("")
        self.resolution_comboBox.addItem("")
        self.resolution_comboBox.addItem("")
        self.resolution_comboBox.addItem("")
        self.resolution_comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.resolution_comboBox)
        self.line_4 = QtGui.QFrame(widget)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_2.addWidget(self.line_4)
        self.assert_comboBox = QtGui.QComboBox(widget)
        self.assert_comboBox.setObjectName("assert_comboBox")
        self.assert_comboBox.addItem("")
        self.assert_comboBox.addItem("")
        self.assert_comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.assert_comboBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.splitter = QtGui.QSplitter(widget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.graph_frame = QtGui.QFrame(self.splitter)
        self.graph_frame.setMinimumSize(QtCore.QSize(300, 300))
        self.graph_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.graph_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.graph_frame.setObjectName("graph_frame")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.treeWidget_2 = QtGui.QTreeWidget(self.layoutWidget)
        self.treeWidget_2.setMaximumSize(QtCore.QSize(900, 16777215))
        self.treeWidget_2.setObjectName("treeWidget_2")
        self.gridLayout.addWidget(self.treeWidget_2, 1, 1, 1, 1)
        self.treeWidget_1 = QtGui.QTreeWidget(self.layoutWidget)
        self.treeWidget_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.treeWidget_1.setObjectName("treeWidget_1")
        self.gridLayout.addWidget(self.treeWidget_1, 1, 0, 1, 1)
        self.global_rb = QtGui.QRadioButton(self.layoutWidget)
        self.global_rb.setObjectName("global_rb")
        self.gridLayout.addWidget(self.global_rb, 0, 0, 1, 1)
        self.show_rb = QtGui.QRadioButton(self.layoutWidget)
        self.show_rb.setObjectName("show_rb")
        self.gridLayout.addWidget(self.show_rb, 0, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.frame_details = QtGui.QFrame(self.layoutWidget)
        self.frame_details.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_details.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_details.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_details.setObjectName("frame_details")
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_details)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.showname_label = QtGui.QLabel(self.frame_details)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.showname_label.setFont(font)
        self.showname_label.setObjectName("showname_label")
        self.horizontalLayout_4.addWidget(self.showname_label)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.shotnameandtaskname_label = QtGui.QLabel(self.frame_details)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.shotnameandtaskname_label.setFont(font)
        self.shotnameandtaskname_label.setObjectName("shotnameandtaskname_label")
        self.horizontalLayout_5.addWidget(self.shotnameandtaskname_label)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.frame_label = QtGui.QLabel(self.frame_details)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.frame_label.setFont(font)
        self.frame_label.setObjectName("frame_label")
        self.horizontalLayout_6.addWidget(self.frame_label)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.resolution_label = QtGui.QLabel(self.frame_details)
        self.resolution_label.setObjectName("resolution_label")
        self.horizontalLayout_8.addWidget(self.resolution_label)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.priority_label = QtGui.QLabel(self.frame_details)
        self.priority_label.setObjectName("priority_label")
        self.horizontalLayout_7.addWidget(self.priority_label)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem11)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem12)
        self.script_size_label = QtGui.QLabel(self.frame_details)
        self.script_size_label.setObjectName("script_size_label")
        self.horizontalLayout_9.addWidget(self.script_size_label)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem13)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem14)
        self.asset_class_label = QtGui.QLabel(self.frame_details)
        self.asset_class_label.setObjectName("asset_class_label")
        self.horizontalLayout_10.addWidget(self.asset_class_label)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem15)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem16)
        self.task_name_label = QtGui.QLabel(self.frame_details)
        self.task_name_label.setObjectName("task_name_label")
        self.horizontalLayout_11.addWidget(self.task_name_label)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem17)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.outputpath_textbox = QtGui.QTextBrowser(self.frame_details)
        self.outputpath_textbox.setObjectName("outputpath_textbox")
        self.verticalLayout.addWidget(self.outputpath_textbox)
        self.scriptpath_textbox = QtGui.QTextBrowser(self.frame_details)
        self.scriptpath_textbox.setObjectName("scriptpath_textbox")
        self.verticalLayout.addWidget(self.scriptpath_textbox)
        self.horizontalLayout_3.addWidget(self.frame_details)
        self.verticalLayout_2.addWidget(self.splitter)
        self.label = QtGui.QLabel(widget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        widget.setWindowTitle(QtGui.QApplication.translate("widget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.filter_label.setText(QtGui.QApplication.translate("widget", "Filter :", None, QtGui.QApplication.UnicodeUTF8))
        self.all_rb.setText(QtGui.QApplication.translate("widget", "ALL", None, QtGui.QApplication.UnicodeUTF8))
        self.comp_rb.setText(QtGui.QApplication.translate("widget", "Comp", None, QtGui.QApplication.UnicodeUTF8))
        self.mm_rb.setText(QtGui.QApplication.translate("widget", "MM", None, QtGui.QApplication.UnicodeUTF8))
        self.paint_rb.setText(QtGui.QApplication.translate("widget", "Paint", None, QtGui.QApplication.UnicodeUTF8))
        self.roto_rb.setText(QtGui.QApplication.translate("widget", "Roto", None, QtGui.QApplication.UnicodeUTF8))
        self.others_rb.setText(QtGui.QApplication.translate("widget", "Others", None, QtGui.QApplication.UnicodeUTF8))
        self.refresh_Button.setText(QtGui.QApplication.translate("widget", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.hide_checkbox.setText(QtGui.QApplication.translate("widget", "Hide Details", None, QtGui.QApplication.UnicodeUTF8))
        self.start_date_lineEdit.setPlaceholderText(QtGui.QApplication.translate("widget", "Start Date", None, QtGui.QApplication.UnicodeUTF8))
        self.start_date_toolButton.setText(QtGui.QApplication.translate("widget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.end_datelineEdit.setPlaceholderText(QtGui.QApplication.translate("widget", "End Date", None, QtGui.QApplication.UnicodeUTF8))
        self.end_date_toolButton.setText(QtGui.QApplication.translate("widget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.render_comboBox.setItemText(0, QtGui.QApplication.translate("widget", "Select Render Type", None, QtGui.QApplication.UnicodeUTF8))
        self.render_comboBox.setItemText(1, QtGui.QApplication.translate("widget", "BG", None, QtGui.QApplication.UnicodeUTF8))
        self.render_comboBox.setItemText(2, QtGui.QApplication.translate("widget", "Local", None, QtGui.QApplication.UnicodeUTF8))
        self.render_comboBox.setItemText(3, QtGui.QApplication.translate("widget", "SMEDGE", None, QtGui.QApplication.UnicodeUTF8))
        self.node_comboBox.setItemText(0, QtGui.QApplication.translate("widget", "Select Node Type", None, QtGui.QApplication.UnicodeUTF8))
        self.node_comboBox.setItemText(1, QtGui.QApplication.translate("widget", "oven_render", None, QtGui.QApplication.UnicodeUTF8))
        self.node_comboBox.setItemText(2, QtGui.QApplication.translate("widget", "package", None, QtGui.QApplication.UnicodeUTF8))
        self.node_comboBox.setItemText(3, QtGui.QApplication.translate("widget", "pre_render", None, QtGui.QApplication.UnicodeUTF8))
        self.node_comboBox.setItemText(4, QtGui.QApplication.translate("widget", "qc_render", None, QtGui.QApplication.UnicodeUTF8))
        self.node_comboBox.setItemText(5, QtGui.QApplication.translate("widget", "write", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_comboBox.setItemText(0, QtGui.QApplication.translate("widget", "Select Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_comboBox.setItemText(1, QtGui.QApplication.translate("widget", "1K", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_comboBox.setItemText(2, QtGui.QApplication.translate("widget", "2K", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_comboBox.setItemText(3, QtGui.QApplication.translate("widget", "3k", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_comboBox.setItemText(4, QtGui.QApplication.translate("widget", "4K", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_comboBox.setItemText(5, QtGui.QApplication.translate("widget", "5k", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_comboBox.setItemText(6, QtGui.QApplication.translate("widget", "6K", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_comboBox.setItemText(7, QtGui.QApplication.translate("widget", "7K", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_comboBox.setItemText(8, QtGui.QApplication.translate("widget", "8K", None, QtGui.QApplication.UnicodeUTF8))
        self.assert_comboBox.setItemText(0, QtGui.QApplication.translate("widget", "Select Asset Class", None, QtGui.QApplication.UnicodeUTF8))
        self.assert_comboBox.setItemText(1, QtGui.QApplication.translate("widget", "mid", None, QtGui.QApplication.UnicodeUTF8))
        self.assert_comboBox.setItemText(2, QtGui.QApplication.translate("widget", "out", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.headerItem().setText(0, QtGui.QApplication.translate("widget", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.headerItem().setText(1, QtGui.QApplication.translate("widget", "Frame Count", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.headerItem().setText(2, QtGui.QApplication.translate("widget", "Show Name", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.headerItem().setText(3, QtGui.QApplication.translate("widget", "Shot Name", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.headerItem().setText(4, QtGui.QApplication.translate("widget", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_2.headerItem().setText(5, QtGui.QApplication.translate("widget", "Time", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_1.headerItem().setText(0, QtGui.QApplication.translate("widget", "Artist", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_1.headerItem().setText(1, QtGui.QApplication.translate("widget", "File Count", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_1.headerItem().setText(2, QtGui.QApplication.translate("widget", "Frame Count", None, QtGui.QApplication.UnicodeUTF8))
        self.global_rb.setText(QtGui.QApplication.translate("widget", "Global", None, QtGui.QApplication.UnicodeUTF8))
        self.show_rb.setText(QtGui.QApplication.translate("widget", "Show", None, QtGui.QApplication.UnicodeUTF8))
        self.showname_label.setText(QtGui.QApplication.translate("widget", "ShowName", None, QtGui.QApplication.UnicodeUTF8))
        self.shotnameandtaskname_label.setText(QtGui.QApplication.translate("widget", "ShotName_TaskName", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_label.setText(QtGui.QApplication.translate("widget", "1001-1100 / 99", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution_label.setText(QtGui.QApplication.translate("widget", "Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.priority_label.setText(QtGui.QApplication.translate("widget", "priority", None, QtGui.QApplication.UnicodeUTF8))
        self.script_size_label.setText(QtGui.QApplication.translate("widget", "script_size", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_class_label.setText(QtGui.QApplication.translate("widget", "asset_class", None, QtGui.QApplication.UnicodeUTF8))
        self.task_name_label.setText(QtGui.QApplication.translate("widget", "task_name", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("widget", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))

